# name: GitHub to Confluence

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# env:
#   CONFLUENCE_TOKEN: ${{ secrets.ATLASSIAN_CLOUD_TOKEN }}

# jobs:
#   setup-build-publish:
#     name: Translate and publish
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout sources
#       - uses: actions/checkout@v3

#       # - name: Run action gh2cf
#       #   uses: ingka-group-digital/github2confluence@v1.0
#       #   with:
#       #     confluence_host: "https://confluence.build.ingka.ikea.com/rest/api"
#       #     github_f: "confluence"
#       #     space: "VIRAJ8"
#       #     parent_id: "622465491"
#       #     #parent_title: "Drafts to be published"
#       #     confluence_token: ${{ env.CONFLUENCE_TOKEN }}

name: Tag Production Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release name
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    name: tag&release
    steps:
      - uses: actions/checkout@v2.3.4
      
# #      https://github.com/marketplace/actions/github-tag
#       - name: Create and push tag
#         id: tag_version
#         uses: mathieudutour/github-tag-action@v6.0
#         with:
#           github_token: ${{ secrets.PAT_GITHUB_TOKEN }}
#           tag_prefix: "RELTP_FE_"
#           custom_tag: ${{ github.event.inputs.tag_name }}

#      https://github.com/marketplace/actions/github-tag
#      - name: Create and push tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          tag_prefix: "RELTP_FE_"
#          custom_tag: ${{ github.event.inputs.tag_name }}

      - name: check the git version
        run: |
           echo $(git log --merges)

           #echo $(git log)


      - name: Run the commit log command
        run: |
           echo "BRANCH_NAME=$(git log --date=short --format='%s' --merges | awk {'print$14}' | awk -F ':' {'print$1'})" >> $GITHUB_ENV
            
           echo $BRANCH_NAME


      - name: test echo 
        run: |
           echo "this is workring"
